test

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -114,6 +114,8 @@ jobs:
                         --password '${{ secrets.VPN_PASSWORD }}' \
                         --dh dh5 \
                         --pfs dh5;   
+                    sleep 10  # Esperar conexión
+                    ping -c 4 bmecvmfcorcd04.azurecr.io || (echo "VPN connection failed"; exit 1)
 
             # -
             #     name: Login to Docker Hub
@@ -130,8 +132,19 @@ jobs:
                 name: Login to ACR
                 if: ${{ 'success' == steps.vpn-connect.conclusion}}
                 run: |
-                    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ vars.DOCKER_REGISTRY }} --username ${{ vars.DOCKER_USERNAME }} --password-stdin || exit 1
                     echo "Successfully logged in to ACR"
+                    for i in {1..3}; do
+                        echo "Attempt $i to login to ACR"
+                        if echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ vars.DOCKER_REGISTRY }} \
+                            --username ${{ vars.DOCKER_USERNAME }} \
+                            --password-stdin; then
+                            echo "Login successful"
+                            exit 0
+                        fi
+                        sleep 5
+                    done
+                    echo "ACR login failed after 3 attempts"
+                    exit 1
             # -
             #     name: 'Synchronize database'
             #     run: |
