fix

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -34,40 +34,41 @@ jobs:
                 uses: 'actions/checkout@main'
 
             -
-                  name: 'Install VPN client'
-                  run: sudo apt-get install vpnc
+              name: 'Azure login'
+              run: docker compose -f compose.yaml run --rm cli az login -u '${{ secrets.AZURE_WEB_APP_CONTAINER_USER }}' -p '${{ secrets.AZURE_WEB_APP_CONTAINER_PASSWORD }}'
+  
+            # -
+            #       name: 'Install VPN client'
+            #       run: sudo apt-get install vpnc
 
-            -
-                name: 'Connect VPN'
-                id: vpn-connect
-                run: |
-                    sudo vpnc \
-                        --gateway 192.100.176.95 \
-                        --id VPNADTmp \
-                        --secret '${{ secrets.VPN_SECRET }}' \
-                        --username '${{ vars.VPN_USER }}' \
-                        --password '${{ secrets.VPN_PASSWORD }}' \
-                        --dh dh5 \
-                        --pfs dh5;
-            -
-                name: 'Azure login'
-                run: docker compose -f compose.yaml run --rm cli az login -u '${{ secrets.AZURE_WEB_APP_CONTAINER_USER }}' -p '${{ secrets.AZURE_WEB_APP_CONTAINER_PASSWORD }}'
+            # -
+            #     name: 'Connect VPN'
+            #     id: vpn-connect
+            #     run: |
+            #         sudo vpnc \
+            #             --gateway 192.100.176.95 \
+            #             --id VPNADTmp \
+            #             --secret '${{ secrets.VPN_SECRET }}' \
+            #             --username '${{ vars.VPN_USER }}' \
+            #             --password '${{ secrets.VPN_PASSWORD }}' \
+            #             --dh dh5 \
+            #             --pfs dh5;
+            # -
+            #     name: Login to Docker Hub
+            #     uses: docker/login-action@v3
+            #     with:
+            #         registry: ${{ vars.DOCKER_REGISTRY }}
+            #         username: ${{ vars.DOCKER_USERNAME }}
+            #         password: ${{ secrets.DOCKER_PASSWORD }}
+            # -
+            #     name: 'Azure logout'
+            #     run: docker compose -f compose.yaml run --rm cli az logout'
 
-            -
-                name: Login to Docker Hub
-                uses: docker/login-action@v3
-                with:
-                    registry: ${{ vars.DOCKER_REGISTRY }}
-                    username: ${{ vars.DOCKER_USERNAME }}
-                    password: ${{ secrets.DOCKER_PASSWORD }}
-            -
-                name: 'Azure logout'
-                run: docker compose -f compose.yaml run --rm cli az logout'
+            # -
+            #       name: 'Disconnect VPN'
+            #       if: ${{ (success() || failure()) && steps.vpn-connect.conclusion == 'success' }}
+            #       run: sudo vpnc-disconnect
 
-            -
-                  name: 'Disconnect VPN'
-                  if: ${{ (success() || failure()) && steps.vpn-connect.conclusion == 'success' }}
-                  run: sudo vpnc-disconnect
             # -
             #     name: 'Download Docker artifacts'
             #     uses: 'actions/download-artifact@v4'
