temoral

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -115,7 +115,23 @@ jobs:
                         --dh dh5 \
                         --pfs dh5;   
                     sleep 10  # Esperar conexión
+                    # ping -c 4 bmecvmfcorcd04.azurecr.io || (echo "VPN connection failed"; exit 1)
 
+            # -
+            #     name: Login to Docker Hub
+            #     uses: docker/login-action@v3
+            #     with:
+            #         # registry: <registry-name>.azurecr.io
+            #         # registry: bmecvmfcorcd04.azurecr.io
+            #         registry: ${{ vars.DOCKER_REGISTRY }}
+            #         username: ${{ vars.DOCKER_USERNAME }}
+            #         password: ${{ secrets.DOCKER_PASSWORD }}
+            #         ecr: false
+
+            -
+                name: Login to ACR
+                if: ${{ 'success' == steps.vpn-connect.conclusion}}
+                run: |
                     echo "Successfully logged in to ACR"
                     for i in {1..3}; do
                         echo "Attempt $i to login to ACR"
