vpn

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -76,27 +76,68 @@ jobs:
                   id: vpn-installation
                   run: sudo apt-get install vpnc
 
-            -
-                name: 'Connect VPN'
-                id: vpn-connect
-                if: ${{ 'success' == steps.vpn-installation.conclusion}}
-                run: |
-                    sudo vpnc \
-                        --gateway 192.100.176.95 \
-                        --id VPNADTmp \
-                        --secret '${{ secrets.VPN_SECRET }}' \
-                        --username '${{ vars.VPN_USER }}' \
-                        --password '${{ secrets.VPN_PASSWORD }}' \
-                        --dh dh5 \
-                        --pfs dh5;
+            # -
+            #     name: 'Connect VPN'
+            #     id: vpn-connect
+            #     if: ${{ 'success' == steps.vpn-installation.conclusion}}
+            #     run: |
+            #         sudo vpnc \
+            #             --gateway 192.100.176.95 \
+            #             --id VPNADTmp \
+            #             --secret '${{ secrets.VPN_SECRET }}' \
+            #             --username '${{ vars.VPN_USER }}' \
+            #             --password '${{ secrets.VPN_PASSWORD }}' \
+            #             --dh dh5 \
+            #             --pfs dh5;
 
-                    # Check VPN conexion.
-                    if ip a | grep -q "tun"; then
-                        echo "VPN connected successfully";
-                    else
-                        echo "VPN connection failed" >&2;
+            #         # Check VPN conexion.
+            #         if ip a | grep -q "tun"; then
+            #             echo "VPN connected successfully";
+            #         else
+            #             echo "VPN connection failed" >&2;
+            #             exit 1;
+            #         fi
+
+            - 
+                name: Connect to Azure VPN
+                id: vpn-connect
+                run: |
+                    echo ""
+                    echo "****************************************************************************"
+                    echo "Connecting to Azure VPN"
+                      
+                    attempts=0
+                    max_attempts=5
+                  
+                    while [ $attempts -lt $max_attempts ]; do
+                        sudo vpnc \
+                            --gateway 192.100.176.95 \
+                            --id VPNADTmp \
+                            --secret '${{ secrets.VPN_SECRET }}' \
+                            --username '${{ vars.VPN_USER }}' \
+                            --password '${{ secrets.VPN_PASSWORD }}' \
+                            --dh dh5 \
+                            --pfs dh5;
+                    
+                        echo "pase del comando vpnc (Attempt $((attempts + 1)) of $max_attempts)"
+                  
+                        # Verificar si la conexión fue exitosa
+                        if [ $? -eq 0 ]; then
+                            break;  # Éxito, salir del loop.
+                        else
+                            attempts=$((attempts + 1))
+                            echo "Connection attempt failed (Attempt $attempts of $max_attempts)"
+                            sleep 5;  # Esperar antes de reintentar
+                        fi
+                    done
+                  
+                    if [ $attempts -eq $max_attempts ]; then
+                        echo "Failed to connect after $max_attempts attempts. Exiting.";
                         exit 1;
                     fi
+
+                    echo "VPN connected"
+                  
 
             # -
             #     name: 'Synchronize database'
